#!/bin/sh -e
#

# Create a default log directory and file for the specified user.
#
# This is particularly useful for all the projects that make use of the
# snaplogger library.
#
# param[in] $1  package name
# param[in] $2  user name
# param[in] $3  group name
# param[in] $4  secure flag (true or false, defaults to false if not specified)
#
prepare_log_directories() {
    PACKAGE_NAME=$1
    USER_NAME=$2
    GROUP_NAME=$3
    SECURE=$4

    LOG_DIR=/var/log/${PACKAGE_NAME}
    LOG_FILE=${LOG_DIR}/${PACKAGE_NAME}.log
    mkdir -p ${LOG_DIR}
    touch ${LOG_FILE}
    chown ${USER_NAME}:${GROUP_NAME} ${LOG_FILE}
    chmod 640 ${LOG_FILE}

    if test -n "${SECURE}" && ${SECURE}
    then
        SECURE_LOG_DIR=${LOG_DIR}/secure
        SECURE_LOG_FILE=${SECURE_LOG_DIR}/${PACKAGE_NAME}.log
        mkdir -p ${SECURE_LOG_DIR}
        touch ${SECURE_LOG_FILE}
        chown ${USER_NAME}:${GROUP_NAME} ${SECURE_LOG_FILE}
        chmod 640 ${SECURE_LOG_FILE}
    fi
}


# vim: ts=4 sw=4 et
